// Code generated by Ridu from ridu.schema.json. DO NOT EDIT.

import { createClient as createRuntimeClient } from "@riducms/sdk";
import type { AuthCollectionSlug, ClientOptions, RiduClient } from "@riducms/sdk";

export type ID = string;

export interface ScalarWhere<Value> {
	equals?: Value;
	notEquals?: Value;
	greaterThan?: Value;
	greaterThanEqual?: Value;
	lessThan?: Value;
	lessThanEqual?: Value;
	contains?: Value extends string ? string : never;
	like?: Value extends string ? string : never;
	in?: readonly Value[];
	exists?: boolean;
}

export type TimestampWhere = Omit<ScalarWhere<string>, "contains" | "like">;

export interface MultiSelectWhere<Value extends string> {
	contains?: Value;
	exists?: boolean;
}

export interface ExistsWhere {
	exists?: boolean;
}

export interface Admins {
	id: ID;
	createdAt: string;
	updatedAt: string;
	"email"?: string;
}

export interface AdminsCreate {
	"email": string;
}

export interface AdminsUpdate {
	"email"?: string;
}

export interface AdminsWhere {
	and?: readonly AdminsWhere[];
	or?: readonly AdminsWhere[];
	not?: AdminsWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	"email"?: ScalarWhere<string>;
}

export interface AdminsSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"email"?: boolean;
}

export interface AdminsPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"email"?: boolean;
}

export type AdminsPopulate = Record<string, never>;

export type AdminsPopulateOutput = Record<string, never>;

export type AdminsValidationPath = "email";

export interface Users {
	id: ID;
	createdAt: string;
	updatedAt: string;
	"email"?: string;
	"displayName"?: string;
	"groupMutationVersion"?: number | null;
}

export interface UsersCreate {
	"email": string;
	"displayName": string;
	"groupMutationVersion"?: number | null;
}

export interface UsersUpdate {
	"email"?: string;
	"displayName"?: string;
	"groupMutationVersion"?: number | null;
}

export interface UsersWhere {
	and?: readonly UsersWhere[];
	or?: readonly UsersWhere[];
	not?: UsersWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	"email"?: ScalarWhere<string>;
	"displayName"?: ScalarWhere<string>;
}

export interface UsersSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"email"?: boolean;
	"displayName"?: boolean;
	"groupMutationVersion"?: boolean;
}

export interface UsersPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	"email"?: boolean;
	"displayName"?: boolean;
	"groupMutationVersion"?: boolean;
}

export type UsersPopulate = Record<string, never>;

export type UsersPopulateOutput = Record<string, never>;

export type UsersValidationPath = "email" | "displayName" | "groupMutationVersion";

export interface Groups {
	id: ID;
	createdAt: string;
	updatedAt: string;
	_status: "published";
	_revision: number;
	"owner"?: ID | Users;
	"name"?: string;
	"rank"?: string;
	"sharingEnabled"?: boolean | null;
	"shareVersion"?: number | null;
}

export interface GroupsCreate {
	"owner": ID;
	"name": string;
	"rank": string;
	"sharingEnabled"?: boolean | null;
	"shareVersion"?: number | null;
}

export interface GroupsUpdate {
	"owner"?: ID;
	"name"?: string;
	"rank"?: string;
	"sharingEnabled"?: boolean | null;
	"shareVersion"?: number | null;
}

export interface GroupsWhere {
	and?: readonly GroupsWhere[];
	or?: readonly GroupsWhere[];
	not?: GroupsWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	_status?: ScalarWhere<"published">;
	"owner"?: ScalarWhere<ID>;
	"name"?: ScalarWhere<string>;
	"rank"?: ScalarWhere<string>;
	"sharingEnabled"?: ScalarWhere<boolean>;
	"shareVersion"?: ScalarWhere<number>;
}

export interface GroupsSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_status?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"name"?: boolean;
	"rank"?: boolean;
	"sharingEnabled"?: boolean;
	"shareVersion"?: boolean;
}

export interface GroupsPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_status?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"name"?: boolean;
	"rank"?: boolean;
	"sharingEnabled"?: boolean;
	"shareVersion"?: boolean;
}

export interface GroupsPopulate {
	"owner"?: boolean | UsersPopulationSelect | { depth?: number; select?: UsersPopulationSelect };
}

export interface GroupsPopulateOutput {
	"owner": ID | Users;
}

export type GroupsValidationPath = "owner" | "name" | "rank" | "sharingEnabled" | "shareVersion";

export interface Assets {
	id: ID;
	createdAt: string;
	updatedAt: string;
	_revision: number;
	"owner"?: ID | Users;
	"group"?: ID | Groups;
	"alt"?: string | null;
	"filename"?: string;
	"mimeType"?: string;
	"filesize"?: number;
	"url"?: string;
	"objectKey"?: string;
	"width"?: number | null;
	"height"?: number | null;
	"source"?: unknown | null;
	"sizes"?: unknown | null;
	"focalX"?: number | null;
	"focalY"?: number | null;
	"cropX"?: number | null;
	"cropY"?: number | null;
	"cropWidth"?: number | null;
	"cropHeight"?: number | null;
}

export interface AssetsCreate {
	"owner": ID;
	"group": ID;
	"alt"?: string | null;
}

export interface AssetsUpdate {
	"owner"?: ID;
	"group"?: ID;
	"alt"?: string | null;
}

export interface AssetsWhere {
	and?: readonly AssetsWhere[];
	or?: readonly AssetsWhere[];
	not?: AssetsWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	"owner"?: ScalarWhere<ID>;
	"group"?: ScalarWhere<ID>;
	"alt"?: ScalarWhere<string>;
	"filename"?: ScalarWhere<string>;
	"mimeType"?: ScalarWhere<string>;
	"filesize"?: ScalarWhere<number>;
	"url"?: ScalarWhere<string>;
	"objectKey"?: ScalarWhere<string>;
	"width"?: ScalarWhere<number>;
	"height"?: ScalarWhere<number>;
	"source"?: ScalarWhere<unknown>;
	"sizes"?: ScalarWhere<unknown>;
	"focalX"?: ScalarWhere<number>;
	"focalY"?: ScalarWhere<number>;
	"cropX"?: ScalarWhere<number>;
	"cropY"?: ScalarWhere<number>;
	"cropWidth"?: ScalarWhere<number>;
	"cropHeight"?: ScalarWhere<number>;
}

export interface AssetsSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"group"?: boolean;
	"alt"?: boolean;
	"filename"?: boolean;
	"mimeType"?: boolean;
	"filesize"?: boolean;
	"url"?: boolean;
	"objectKey"?: boolean;
	"width"?: boolean;
	"height"?: boolean;
	"source"?: boolean;
	"sizes"?: boolean;
	"focalX"?: boolean;
	"focalY"?: boolean;
	"cropX"?: boolean;
	"cropY"?: boolean;
	"cropWidth"?: boolean;
	"cropHeight"?: boolean;
}

export interface AssetsPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"group"?: boolean;
	"alt"?: boolean;
	"filename"?: boolean;
	"mimeType"?: boolean;
	"filesize"?: boolean;
	"url"?: boolean;
	"objectKey"?: boolean;
	"width"?: boolean;
	"height"?: boolean;
	"source"?: boolean;
	"sizes"?: boolean;
	"focalX"?: boolean;
	"focalY"?: boolean;
	"cropX"?: boolean;
	"cropY"?: boolean;
	"cropWidth"?: boolean;
	"cropHeight"?: boolean;
}

export interface AssetsPopulate {
	"owner"?: boolean | UsersPopulationSelect | { depth?: number; select?: UsersPopulationSelect };
	"group"?: boolean | GroupsPopulationSelect | { depth?: number; select?: GroupsPopulationSelect };
}

export interface AssetsPopulateOutput {
	"owner": ID | Users;
	"group": ID | Groups;
}

export type AssetsValidationPath = "owner" | "group" | "alt";

export interface Bookmarks {
	id: ID;
	createdAt: string;
	updatedAt: string;
	_status: "published";
	_revision: number;
	"owner"?: ID | Users;
	"group"?: ID | Groups;
	"kind"?: "link" | "text" | "media";
	"position"?: string;
	"url"?: string | null;
	"title"?: string | null;
	"description"?: string | null;
	"favicon"?: string | null;
	"previewImage"?: string | null;
	"videoProvider"?: string | null;
	"videoID"?: string | null;
	"text"?: string | null;
	"caption"?: string | null;
	"images"?: Array<ID | Assets> | null;
}

export interface BookmarksCreate {
	"owner": ID;
	"group": ID;
	"kind": "link" | "text" | "media";
	"position": string;
	"url"?: string | null;
	"title"?: string | null;
	"description"?: string | null;
	"favicon"?: string | null;
	"previewImage"?: string | null;
	"videoProvider"?: string | null;
	"videoID"?: string | null;
	"text"?: string | null;
	"caption"?: string | null;
	"images"?: Array<ID> | null;
}

export interface BookmarksUpdate {
	"owner"?: ID;
	"group"?: ID;
	"kind"?: "link" | "text" | "media";
	"position"?: string;
	"url"?: string | null;
	"title"?: string | null;
	"description"?: string | null;
	"favicon"?: string | null;
	"previewImage"?: string | null;
	"videoProvider"?: string | null;
	"videoID"?: string | null;
	"text"?: string | null;
	"caption"?: string | null;
	"images"?: Array<ID> | null;
}

export interface BookmarksWhere {
	and?: readonly BookmarksWhere[];
	or?: readonly BookmarksWhere[];
	not?: BookmarksWhere;
	id?: ScalarWhere<ID>;
	createdAt?: TimestampWhere;
	updatedAt?: TimestampWhere;
	_status?: ScalarWhere<"published">;
	"owner"?: ScalarWhere<ID>;
	"group"?: ScalarWhere<ID>;
	"kind"?: ScalarWhere<"link" | "text" | "media">;
	"position"?: ScalarWhere<string>;
	"url"?: ScalarWhere<string>;
	"title"?: ScalarWhere<string>;
	"description"?: ScalarWhere<string>;
	"favicon"?: ScalarWhere<string>;
	"previewImage"?: ScalarWhere<string>;
	"videoProvider"?: ScalarWhere<string>;
	"videoID"?: ScalarWhere<string>;
	"text"?: ScalarWhere<string>;
	"caption"?: ScalarWhere<string>;
	"images"?: ScalarWhere<ID>;
}

export interface BookmarksSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_status?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"group"?: boolean;
	"kind"?: boolean;
	"position"?: boolean;
	"url"?: boolean;
	"title"?: boolean;
	"description"?: boolean;
	"favicon"?: boolean;
	"previewImage"?: boolean;
	"videoProvider"?: boolean;
	"videoID"?: boolean;
	"text"?: boolean;
	"caption"?: boolean;
	"images"?: boolean;
}

export interface BookmarksPopulationSelect {
	id?: boolean;
	createdAt?: boolean;
	updatedAt?: boolean;
	_status?: boolean;
	_revision?: boolean;
	"owner"?: boolean;
	"group"?: boolean;
	"kind"?: boolean;
	"position"?: boolean;
	"url"?: boolean;
	"title"?: boolean;
	"description"?: boolean;
	"favicon"?: boolean;
	"previewImage"?: boolean;
	"videoProvider"?: boolean;
	"videoID"?: boolean;
	"text"?: boolean;
	"caption"?: boolean;
	"images"?: boolean;
}

export interface BookmarksPopulate {
	"owner"?: boolean | UsersPopulationSelect | { depth?: number; select?: UsersPopulationSelect };
	"group"?: boolean | GroupsPopulationSelect | { depth?: number; select?: GroupsPopulationSelect };
	"images"?: boolean | AssetsPopulationSelect | { depth?: number; select?: AssetsPopulationSelect };
}

export interface BookmarksPopulateOutput {
	"owner": ID | Users;
	"group": ID | Groups;
	"images": Array<ID | Assets> | null;
}

export type BookmarksValidationPath = "owner" | "group" | "kind" | "position" | "url" | "title" | "description" | "favicon" | "previewImage" | "videoProvider" | "videoID" | "text" | "caption" | "images" | `images.${number}`;

export interface RiduConfig {
	locale: never;
	collections: {
		"admins": {
			slug: "admins";
			auth: true;
			upload: false;
			versions: false;
			drafts: false;
			trash: false;
			output: Admins;
			create: AdminsCreate;
			update: AdminsUpdate;
			where: AdminsWhere;
			select: AdminsSelect;
			populate: AdminsPopulate;
			populateOutput: AdminsPopulateOutput;
			validationPath: AdminsValidationPath;
		};
		"users": {
			slug: "users";
			auth: true;
			upload: false;
			versions: false;
			drafts: false;
			trash: false;
			output: Users;
			create: UsersCreate;
			update: UsersUpdate;
			where: UsersWhere;
			select: UsersSelect;
			populate: UsersPopulate;
			populateOutput: UsersPopulateOutput;
			validationPath: UsersValidationPath;
		};
		"groups": {
			slug: "groups";
			auth: false;
			upload: false;
			versions: true;
			drafts: false;
			trash: false;
			output: Groups;
			create: GroupsCreate;
			update: GroupsUpdate;
			where: GroupsWhere;
			select: GroupsSelect;
			populate: GroupsPopulate;
			populateOutput: GroupsPopulateOutput;
			validationPath: GroupsValidationPath;
		};
		"assets": {
			slug: "assets";
			auth: false;
			upload: true;
			versions: false;
			drafts: false;
			trash: false;
			output: Assets;
			create: AssetsCreate;
			update: AssetsUpdate;
			where: AssetsWhere;
			select: AssetsSelect;
			populate: AssetsPopulate;
			populateOutput: AssetsPopulateOutput;
			validationPath: AssetsValidationPath;
		};
		"bookmarks": {
			slug: "bookmarks";
			auth: false;
			upload: false;
			versions: true;
			drafts: false;
			trash: false;
			output: Bookmarks;
			create: BookmarksCreate;
			update: BookmarksUpdate;
			where: BookmarksWhere;
			select: BookmarksSelect;
			populate: BookmarksPopulate;
			populateOutput: BookmarksPopulateOutput;
			validationPath: BookmarksValidationPath;
		};
	};
}

export type CollectionSlug = keyof RiduConfig["collections"];

export function createClient<const DefaultAuth extends AuthCollectionSlug<RiduConfig> = never>(
	options: ClientOptions<DefaultAuth>
): RiduClient<RiduConfig, DefaultAuth> {
	return createRuntimeClient<RiduConfig, DefaultAuth>(options);
}
